# enable the plugin
enabled: true

frequency-representation:
  dyes:
    WHITE: "Whi"
    LIGHT_GRAY: "LGr"
    GRAY: "Gra"
    BLACK: "Bla"
    BROWN: "Bro"
    RED: "Red"
    ORANGE: "Ora"
    YELLOW: "Yel"
    LIME: "Lim"
    GREEN: "Gre"
    CYAN: "Cya"
    LIGHT_BLUE: "LBl"
    BLUE: "Blu"
    PURPLE: "Pur"
    MAGENTA: "Mag"
    PINK: "Pin"
  separating-string: "-"

# Radio
fieldradio:
  audio-filter:
    enabled: true
    LP-alpha: 0.8  # Lower = more muffled
    HP-alpha: 0.85 # Higher = less bass
    noise-floor: 75  # Constant hiss volume
    crackle-chance: 3000 # 1 in 3000 chance per sample

  grace-period: 200000000
  recipe:
    basic:
      enabled: true

      # Use 0 for main frequency and numbers 1 - 9 for subfrequencies,
      # MUST have a main frequency and AT LEAST ONE subfrequency
      shape:
        - "O01"
        - "IAI"
        - "IRI"
      ingredients:
        O: "LIGHTNING_ROD"
        I: "IRON_INGOT"
        R: "REDSTONE"
        A: "AMETHYST_SHARD"